Service:
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: litellm-
    SupplierDeployMetadata:
      ArtifactRelation:
        centos_7:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 新建ECS实例
        Url: 'ros_templates/template1.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: 通过 LiteLLM 可以使用 OpenAI 格式调用所有 LLM API [Bedrock、Huggingface、VertexAI、TogetherAI、Azure、OpenAI、Groq 等]。
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: litellm
    Description: litellm
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: aliyun_3_x64_20G_alibase_20240819.vhd
    SystemDiskSize: 40
    InstanceType: ecs.c7.2xlarge
    InternetMaxBandwidthOut: 100
    CommandType: RunShellScript
    Timeout: 10800
    CommandContent: |-
        #!/bin/bash
        yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        yum makecache
        yum install -y wget curl unzip git jq
        yum install -y docker-ce
        systemctl enable --now docker.socket

        git clone https://github.com/BerriAI/litellm.git
        cd litellm
        cp .env.example .env
        docker compose up -d